# Build the kube-cache binary
FROM golang:1.15-alpine3.12 AS builder
RUN apk add --update --no-cache musl-dev linux-headers

WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download

COPY api api
COPY internal internal
COPY cmd/kube-cache cmd/kube-cache
ARG BUILD_TAGS='exclude_graphdriver_devicemapper exclude_graphdriver_btrfs btrfs_noversion containers_image_ostree_stub containers_image_openpgp'
RUN set -ex; \
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on \
	go build -o kube-cache -tags "$BUILD_TAGS" \
		-ldflags "-s -w -extldflags '-static'" \
		./cmd/kube-cache


FROM alpine:3.12
COPY --from=builder /workspace/kube-cache /usr/bin/kube-cache
COPY helper/policy.json /etc/containers/
