# Build the dcowfs binary
FROM golang:1.15-alpine3.12 AS builder
RUN apk add --update --no-cache musl-dev linux-headers

WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download

COPY api api
COPY internal internal
COPY cmd/dcowfs cmd/dcowfs
ARG BUILD_TAGS='exclude_graphdriver_devicemapper exclude_graphdriver_btrfs btrfs_noversion containers_image_ostree_stub containers_image_openpgp'
RUN set -ex; \
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on \
	go build -o dcowfs -tags "$BUILD_TAGS" \
		-ldflags "-s -w -extldflags '-static'" \
		./cmd/dcowfs


FROM alpine:3.12
COPY --from=builder /workspace/dcowfs /usr/bin/dcowfs
COPY helper/policy.json /etc/containers/
