# Build the layerfs binary
FROM golang:1.15-alpine3.13 AS builder
RUN apk add --update --no-cache git musl-dev linux-headers

# Fetch dependencies (cached)
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download

# Build
COPY api api
COPY internal/layerfs internal/layerfs
COPY internal/ksync internal/ksync
COPY cmd/layerfs cmd/layerfs
ARG BUILD_TAGS='exclude_graphdriver_devicemapper exclude_graphdriver_btrfs btrfs_noversion containers_image_ostree_stub containers_image_openpgp'
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on \
	go build -o layerfs -tags "$BUILD_TAGS" \
		-ldflags "-s -w -extldflags '-static'" \
		./cmd/layerfs


FROM alpine:3.12
COPY --from=builder /workspace/layerfs /usr/bin/layerfs
COPY helper/policy.json /etc/containers/
