#!/bin/sh

CACHE_NAME="${PVC_ANNOTATION_CACHE_NAME:-$(echo "$PVC_NAME" | sed -E 's/^(.+)-[^-]+$/\1/')}"
VOL_NAME="$(basename "$VOL_DIR")"
export CACHE_ROOT_DIR="$(dirname "$VOL_DIR")"

#cache-provisioner umount "$CACHE_NAME" "$VOL_NAME"

export KUBE_CACHE_STORAGE_ROOT="$(dirname "$VOL_DIR")/.cache"
kube-cache umount "$VOL_DIR" --name "$CACHE_NAME" --container-name "$VOL_NAME" --commit
