#!/bin/sh

#export LAYERFS_NAME="${PVC_ANNOTATION_CACHE_NAME:-`echo "$PVC_NAME" | sed -E 's/^(.+)-[^-]+$/\1/'`}"
#export LAYERFS_NAMESPACE="$PVC_NAMESPACE"
#export LAYERFS_CONTAINER_NAME="`basename "$VOL_DIR"`"
#export LAYERFS_STORAGE_ROOT="`dirname "$VOL_DIR"`/.cache"

layerfs umount "$VOL_DIR" --commit
