#!/bin/sh

# test script:
# - docker run --rm --privileged -v $(pwd)/config/setup:/setup --mount type=bind,source=$(pwd)/testdata,target=/data,bind-propagation=rshared --device /dev/fuse alpine:3.12 sh /setup /data/pv1
# - or for buildah: docker run --rm --privileged -v $(pwd)/config/setup:/setup --mount type=bind,source=$(pwd)/testdata,target=/data,bind-propagation=rshared --entrypoint=/bin/sh mgoltzsche/podman:1.9.3 /setup /data/pv1
# test integration:
# - kustomize build . | kubectl apply -f - && kubectl delete -n cache-storage deploy cached-local-path-provisioner
# - cd ../local-path-provisioner && go build . && ./local-path-provisioner --debug start --config ../jobcachefs/config/config.json --configmap-name cached-local-path-config --provisioner-name mgoltzsche.github.com/cache-provisioner --service-account-name cached-local-path-provisioner-service-account --namespace cache-storage --helper-privileged --helper-image mgoltzsche/podman:1.9.3
# - cd ../pvc-remover && go build . && ./pvc-remover --storage-class cache
# - kubectl apply -f test.yaml

VOLPATH="$1"
VOLNAME="$(basename "$VOLPATH")"
export ROOT_DIR="$(dirname "$VOLPATH")"
export CACHE_DIR="$ROOT_DIR/.cache"

cache-provisioner mount "$VOLNAME"
